# Basic
title: liangzh.tech
subtitle: ä¸ªäººæŠ€æœ¯åšå®¢
welcome_message: <a href="https://wadee.github.io" target="_blank">ğŸ¸âŒ¨ï¸ğŸ¹(à¹‘â€¢Ì€ã…‚â€¢Ì)Ùˆâœ§</a>
description: ä¼¸æ‰‹æ‘˜æ˜Ÿæœªå¿…å¦‚æ„¿ï¼Œä½†ä¸€å®šä¸ä¼šç·æ±¡ä½ çš„æ‰‹.
creator: <a href="https://github.com/wadee">@wadee</a>

url: "http://wadee.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: orange

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: liangzh
    # duoshuo: 
    
# Social
social:
    weibo: flymetothestar
    github: wadee
    mail: liangzehua1989@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
